-- 코드를 작성해주세요

SELECT r.ID, (COUNT(r.ID)-1) AS CHILD_COUNT FROM

((SELECT e1.ID FROM ECOLI_DATA e1 JOIN ECOLI_DATA e2 ON e1.ID = e2.PARENT_ID)
UNION ALL
(SELECT e.ID FROM ECOLI_DATA e)) r

GROUP BY r.ID
ORDER BY r.ID;